name: Test Pull Request

on:
    workflow_call:
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
            - name: Install dependencies
              run: bun install
            - name: Fetch main
              run: git fetch --no-tags --prune --depth=1 origin main:refs/remotes/origin/main 
            - name: Run tests
              working-directory: ./src
              run: bun test
